language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# install dependencies
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
  - poetry install
# run tests
script:
  - source $HOME/.poetry/env
  - poetry run coverage run --source=./tests -m unittest discover -s ./tests
  - poetry run coverage report -m