on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Run tests

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env
        poetry install
    - name: Runs tests
      run: |
        source $HOME/.poetry/env
        poetry run coverage run --source=./tests -m unittest discover -s ./tests
        poetry run coverage report -m
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2